### ISSUE TITLE
Illegal division by zero at plasmidseeker.pl line 409

### ISSUE THREAD

**Issue by danknight** [bioinfo-ut/PlasmidSeeker#1]
Hi,
The example E.coli  data runs perfectly, both using the .sh file and running the commands individually. However, I have tried with at least a dozen of my own fastq files from multiple independent Illumina runs and I get the error below, every time. I see that line 409 relates to 'Filtering high p-value plasmids'. Any ideas what I am doing wrong?

Cheers
Dan

dk@TCD50[PlasmidSeeker] perl plasmidseeker.pl -d db_w20 -i ES1114_1P.fastq -b AM180355.fna -o ES114_results.txt
Loading database...
Converting sample reads to k-mers...
Finding coverage of bacterial isolate...
tmp_list_cov_20_intrsec.list tmp_list_cov_20_intrsec.list
Total size 6513950
Finding intersection
Size 3256975
Sorting
Done
Printing distribution of tmp_bacteria.txt
Initial median 22
tmp_final_20_0_diff1.list tmp_final_20_0_diff1.list
Total size 6482168
Finding intersection
Size 3241084
Sorting
Done
FINAL median 22
Bacteria median coverage is 22
**Illegal division by zero at plasmidseeker.pl line 409.**

**Comment by bioinfo-ut** [comment]
Thanks for the feedback. We will investigate why the problem appears. Could you send us some of your problematic input files?

**Comment by danknight** [comment]
Thanks for looking into this for me. Here is a link to some of my fastqs and the ref I am using.
https://www.dropbox.com/sh/ig2sbi6ov077sgc/AAAXuDf-hE-7edciASgF1nWPa?dl=0
Cheers
Dan

**Comment by SK-N-BE** [comment]
Hei everyone,
I get the same message for those samples for which I suggest that no plasmid is present:

Loading database...
Converting sample reads to k-mers...
Finding coverage of bacterial isolate...
tmp_list_cov_20_intrsec.list tmp_list_cov_20_intrsec.list
Total size 4970470
Finding intersection
Size 2485235
Sorting
Done
Printing distribution of tmp_bacteria.txt
Initial median 34
tmp_final_20_0_diff1.list tmp_final_20_0_diff1.list
Total size 4925904
Finding intersection
Size 2462952
Sorting
Done
FINAL median 34
Bacteria median coverage is 34
Illegal division by zero at plasmidseeker.pl line 409.


Everything is working fine for isolates where I know that a plasmid is present. Thus, may it be possible that this error message indicate that no plasmid could be found (or at least no plasmid with more than 80% identity)?

**Comment by bioinfo-ut** [comment]
We investigated the problem and it seems just as SK-N-BE described - a high-coverage bacterial sample, in which there are no plasmids with over 80% identity. We have changed the code to repair this issue and it should be fine now. Thanks again for bringing it up.

**Comment by SK-N-BE** [comment]
I downloaded the new plasmidseeker.pl. However, when I am running it, I get the following error:

Bareword found where operator expected at plasmidseeker.pl line 30, near "<title>PlasmidSeeker"
	(Missing operator before PlasmidSeeker?)
syntax error at plasmidseeker.pl line 10, near "<"
Unrecognized character \xC2; marked by <-- HERE after at master <-- HERE near column 51 at plasmidseeker.pl line 30.

When I am running "the old" plasmidseeker.pl, everything is fine.

**Comment by bioinfo-ut** [comment]
Hi!

I downloaded new plasmidseeker.pl and was unable to reproduce the error. Can you look into it a little more? Reading the description, the error seems weird as neither line 10 or line 30 of the perl code contains "<" or "<title>PlasmidSeeker". Are you sure you downloaded the right thing?

**Comment by SK-N-BE** [comment]
Hello,
I checked it several times and downloaded several times the new plasmidseeker.pl. However, I am now getting this error message:

syntax error at plasmidseeker.pl line 10, near "<"
Excessively long <> operator at plasmidseeker.pl line 21.

Copying the old plasmidseeker.pl is working fine. I do not know what I am doing wrong.
