### ISSUE TITLE
High P value plasmids clarification

### ISSUE THREAD

**Issue by LeonardosMageiros** [bioinfo-ut/PlasmidSeeker#10]
Hi,

I am using your software against some Klebsiella isolates I am working with and I am a bit confused with my results. Let me explain:

In my output file I have a Estimated bacteria isolate median coverage = 73

In my first cluster of plasmids the first two lines are the following:
97229	114334	85.04%	2.05	9.55192e-10	Klebsiella pneumoniae strain Kpn-1870 plasmid pKP1870-kpc, complete sequence	150	db_w20//plasmid_398.fna_20.list
95867	97130	98.70%	1.95	0	Escherichia coli strain BK28960 plasmid pKpQIL-Ec, complete sequence	142	db_w20//plasmid_873.fna_20.list   
(3 more plasmids follow in the same cluster)

So if I get this correctly the first entry is the longest plasmid, it has double coverage hence the number of copies is 2 and the pvalue is low because of the coverage difference. Please correct me if I have this wrong. 

Now going down to my HIGH P-VALUE PLASMIDS the first entry is the following:
110043	111685	98.53%	2.01	1	Klebsiella pneumoniae subsp. pneumoniae strain KPN_KPC_HUG_07 plasmid p2, complete sequence	147	db_w20//plasmid_7939.fna_20.list

Now to me this seems to be a similar entry as the first entry in my first cluster as they both have similar lengths, similar coverage, similar copy numbers and in based on their description they both contain KPC genes. Still the pvalue of this entry is 1 and I don't understand why this happens or what that means as  there is a difference between the copy number of this entry and the chromosomal copy number. 

Can you please explain why this happens? I can provide my full output if needed. 

Thank you very much for your time
Leonardos

**Comment by martroosaare** [comment]
Hi!

Analyzing plasmids by Blast, they are about 99% identical over 90% of their length, so indeed, very similar plasmids.

The output seems erroneous as the other plasmid should be in the same cluster as the first one. We are looking into what could be causing this error.

**Comment by martroosaare** [comment]
If your input files are not confidential, they would help us greatly to track down this possible bug by running PlasmidSeeker on them ourselves.

**Comment by LeonardosMageiros** [comment]
Here is a wetransfer link with my input files: https://we.tl/t-tUOxOwvk76
You should find a compressed fastq file with my concatenated reads and a fasta file with a reference sequence. 
Let me know if you had any issue getting the files. 

Thank you very much for your time and help!

**Comment by martroosaare** [comment]
What is the exact command you are using to run plasmidseeker? And which file are you using for the -b parameter?

**Comment by LeonardosMageiros** [comment]
Apologies for my late response. 
The command I am using is the following:
perl plasmidseeker.pl -d db_w20/ -i ../harry/SPARK_188_C1.fastq -b ../harry/NTUH-K2044.fasta -o ../SPARK_188_C1_test.out -t 12

As you can see, I give the contigs fasta file (NTUH-K2044.fasta) as an argument for the -b parameter. 

Please let me know if I can help in any other way. 
Thank you very much for your help.
Best
Leonardos

**Comment by LeonardosMageiros** [comment]
Hi, 

I was wondering if you had any update on this issue as I would like to use plasmidseeker for my project. 
Thank you in advance for your time and help

Leonardos

**Comment by mihkelvaher** [comment]
Hi,

Looking at the k-mer distributions of the pKP1870-kpc  and KPN_KPC_HUG_07  plasmids we can see where the difference comes:
![plasmid_398](https://user-images.githubusercontent.com/11218079/54977864-4e1a7400-4fa7-11e9-8ee3-a7029f112c43.png)
![plasmid_7939](https://user-images.githubusercontent.com/11218079/54977871-51156480-4fa7-11e9-83c2-97175408189c.png)
Blue dots indicate the bacterial and red the plasmid's k-mers.

For pKP1870-kpc the peak coverage is clearly different for both distributions and that the plasmid has a higher copy number.

For KPN_KPC_HUG_07 there might be two scenarios:
1) The plasmid has integrated into the bacterial genome (left red curve, same coverage as the bacterial genome) AND a part of it has duplicated (right red curve, 2x as the left curve).
2) The duplication has occurred as described but the plasmid is not integrated into the genome and has exactly the same copy number as the bacterial genome (unlikely)

Further investigation probably requires assembly.

Hope it helps,
Mihkel

**Comment by LeonardosMageiros** [comment]
Mihkel thank you very much for your response. 

So if I get this correctly the fact that I have 18 entries in my hi pvalue plasmids, all with the same coverage (147 or very very close to that number), which is also very close to the coverage of my plasmid clusters is explained by your second graph. 

They are all plasmids that have two picks in their distribution and one of the two picks is similar to the distribution of the chromosomal reads. Is that correct? 

Is the decision of the algorithm to cluster them in the hi pvalue group based on that fact? 

Thank you very much once again. 
Leonardos

**Comment by mihkelvaher** [comment]
The plasmids reported under the high p-value in your sample are probably very closely related judging by how similar are the k-mer percentages, the coverage and the copy number. This means that in reality there is just one plasmid (closely related to the given plasmids) which is probably integrated and of which some part is duplicated.

The decision to cluster into high p-value group is based on the fact that the coverages are a multiple (in this case 1x and 2x for the left and right peak) of the bacterial coverage.

**Comment by LeonardosMageiros** [comment]
Mihkel thank you very much for your very helpful reply.

Can I ask how you created these plots as it might be helpful to show them in my analysis for cases like that? 

Best 
Leonardos

**Comment by mihkelvaher** [comment]
Hi!

We updated PlasmidSeeker with new flags. The flag -k saves 3 additional files for each plasmid (distribution, plot and short summary).

Mihkel

**Comment by LeonardosMageiros** [comment]
Hi Mihkel, 

Thank you very much for your update. 
Trying to run the updated version of PlasmidSeeker (i downloaded only the updated source code of PlasmidSeeker.pl) with the -k flag, gives me the plasmid_distr files but I can not see the plot and the short summary files. 

Am I doing something wrong? I am running the same commands as before, adding the -k in the end. 

Thank you very much in advance for your time and help.

Best 
Leonardos

**Comment by mihkelvaher** [comment]
Hi!

The short summary and plots are generated by the "testfunction.R" script which needs to be updated also. (plasmidseeker.pl and testfunction.R + readme were updated).

Mihkel

**Comment by LeonardosMageiros** [comment]
Works perfectly now. 
Thx a lot Mihkel!
