### ISSUE TITLE
Execute plasmidseeker in multiple input files - output folder flag

### ISSUE THREAD

**Issue by LeonardosMageiros** [bioinfo-ut/PlasmidSeeker#12]
Hi, 

I am trying to create a wrapper script to execute plasmidseeker in a large number of input files at once.

Is there a way to tell plasmidseeker to output the results (of a single run) into a specific folder instead of the current directory? If not would it be easy to implement this feature? It would make the execution of the script much more organized if the results for each input strain could be put into a different folder. 

Also are the tmp files needed after a run is over? Would it be ok if I just delete them when the execution finishes? 

Thank you very much for your time and help
Best 
Leonardos

**Comment by mihkelvaher** [comment]
Hi!

Have you tried the "-o" flag for outputs? For example "... -o ./my_outputs/some_run_1.txt".
The tmp files are safe to delete after the execution finishes.

Regards,
Mihkel

**Comment by LeonardosMageiros** [comment]
Mihkel I am afraid I already tired that and still the output files are printed in the current directory and not in the folder specified in the -o flag. 
Do you think it is an easy fix to implement? 

Thank you very much 
Leonardos

**Comment by mihkelvaher** [comment]
Have you tried creating the output dir beforehand?
Currently, if the output directory does not exist, it shouldn't output even to the current dir.
I'd guessed that the output that you're seeing is from a previous run that is directed to the current dir?

Mihkel

**Comment by LeonardosMageiros** [comment]
Hi Mihkel, 

I will explain what I am doing step by step. 

The contents of the current directory before I execute anything are shown below:
![image](https://user-images.githubusercontent.com/28563735/58160888-342fa180-7c77-11e9-86aa-657153ba28ca.png)

The command I am executed is the following:
plasmidseeker.pl -d ../PlasmidSeeker/db_w20/ -i SPARK_188_C1.fastq -b SPARK_1380_C1.fasta -o ./test/SPARK_188_C1.out -t 12 -k

As you can see from the screenshot below the output files from -k are printed to the current directory and the folder test only contains the SPARK_188_C1.out file. 

![image](https://user-images.githubusercontent.com/28563735/58161513-49590000-7c78-11e9-83db-63dae099f0ee.png)
 
What I would like to have is also the files produced from the -k flag in the test directory (and ideally the tmp files as well). 

Am I doing something wrong and there is already a way to achieve this? 

Thank you very much 
Leonardos

**Comment by mihkelvaher** [comment]
Hi!

All of the files for the given run are now written into the directory where the output file path is given:
`perl plasmidseeker.pl... -o /some/path/THIS_DIR/my_out.txt`
Please update plasmidseeker.pl and testfunction.R

Regards,
Mihkel

**Comment by LeonardosMageiros** [comment]
Works like a clock. Thank you very much for that!
