### ISSUE TITLE
how can I obtain the fasta file sequence for the 8514 plasmid ?

### ISSUE THREAD

**Issue by kjestradag** [bioinfo-ut/PlasmidSeeker#16]

**Comment by martroosaare** [comment]
just download the database (links provided in publication) - it contains both k-mer list files and associated FASTA files.

**Comment by LeonardosMageiros** [comment]
Hi, 

I would like to do exactly the same thing and obtain a fasta file of the plasmids in your db. 
Going in the link of your publication (https://figshare.com/articles/PlasmidSeeker_database_k_20/5497972/1) I can only find a binary version of your database. Is there an alternative link that I am missing to get the fasta file(s)? 

Thank you very much in advance!
Leonardos

**Comment by mihkelvaher** [comment]
Hi,

The file appears to have been gone missing. I've added the multifasta file to http://bioinfo.ut.ee/plasmidseeker/plasmid_db_12jul17.fna.gz

The fasta headers (in plasmid_db_12jul17.fna) and the "names.txt" (which is with the binary files on figshare), contain all of the info needed.
Note that the fasta header also contains the NC accession number if further research is needed.

Regards, 
Mihkel

**Comment by LeonardosMageiros** [comment]
Thank you very much Mihkel. I have the fasta file now!
