### ISSUE TITLE
compressed gz file support

### ISSUE THREAD

**Issue by LeonardosMageiros** [bioinfo-ut/PlasmidSeeker#18]
Hi, 

I am trying to run plasmidseeker using a .gz compressed file and I get the following: 
![image](https://user-images.githubusercontent.com/28563735/61542608-d2eb3b00-aa39-11e9-8400-92713b7ccb93.png)

When I gunzip my input file the executions proceeds normally. Is that normal? Are compressed gz fastq files not supported? 

Thank you very much for your time. 

Best 
Leonardos

**Comment by mihkelvaher** [comment]
Hi,

Compressed files are indeed unsupported. Currently, in the near future, it's not a planned feature to be added.

Mihkel
