### ISSUE TITLE
gt4_wordmap_new: invalid file size (1048576, should be 1429612) Error: Creating the wordmap failed!

### ISSUE THREAD

**Issue by Galib009** [bioinfo-ut/PlasmidSeeker#19]
During plasmid_seeker run i see this -

Converting sample reads to k-mers...
Finding coverage of bacterial isolate...
Bacteria median coverage is 100
**##gt4_wordmap_new: invalid file size (1048576, should be 1429612)
Error: Creating the wordmap failed!**
Plasmids done: 4384 of 4388

but after that everything is okay and result is generated. Does this "creating the wordmap failed" can cause change in result?

**Comment by mihkelvaher** [comment]
The problem is probably due to a corrupt list file.
If the error message was only shown once, it means that one list is corrupt and the corresponding plasmid won't be included in the final result even if it should.

Try downloading/creating the database again and see if the problem persists.
