### ISSUE TITLE
-i [your WGS sample FASTQ file], is it paired or unpaired fastq file?

### ISSUE THREAD

**Issue by ilkaybuysal** [bioinfo-ut/PlasmidSeeker#21]
For running plasmidseeker, we need to provide the fastq file, but I'm not sure if we should provide both R1 and R2 or the unpaired.fq file?
perl plasmidseeker.pl -d [your database dir] -i [your WGS sample FASTQ file] -b [close reference bacterium FASTA file] -o [output file name]

**Comment by mihkelvaher** [comment]
As the copy numbers are estimated using coverages, it's better to ensure good coverage as there are more fluctuations with low coverage.
I'd suggest merging all of the fastq files. Read pairing is not taken into account.

**Comment by ilkaybuysal** [comment]
THanks a lot for your answer! So I should merge MG.R1 and MG.R2 and use it as the input?

**Comment by mihkelvaher** [comment]
Yes.

**Comment by ilkaybuysal** [comment]
Thanks a lot!
