### ISSUE TITLE
Deciding  -b [close reference bacterium FASTA file]

### ISSUE THREAD

**Issue by ilkaybuysal** [bioinfo-ut/PlasmidSeeker#22]
PLasmidseeker asks for -b [close reference bacterium FASTA file]. I'm looking at Lactobacillus gasseri plasmids but there are multiple strains of L.gasseri, I'm not sure how to choose the reference file? https://www.ncbi.nlm.nih.gov/nuccore

**Comment by mihkelvaher** [comment]
The reference bacterium should be similar to the one in the sample which means the strain needs to be identified first. This could be done with [StrainSeeker](https://bioinfo.ut.ee/strainseeker/) or with a similar software or even with mapping.
If a random strain of the same species is provided, the overall results might be less accurate.

**Comment by ilkaybuysal** [comment]
Thanks a lot!
