### ISSUE TITLE
Error: Creating the wordmap failed! Died at plasmidseeker.pl line 156

### ISSUE THREAD

**Issue by ABMolBio** [bioinfo-ut/PlasmidSeeker#25]
Hi, during plasmid_seeker run, I am having this error again and again -

Loading database...
Converting sample reads to k-mers...
Finding coverage of bacterial isolate...
**gt4_wordmap_new: could not mmap file ./16442730219721tmp_closest_32.list
Error: Creating the wordmap failed!
Died at plasmidseeker.pl line 156.****
I have tried with different reference sequence downloaded from NCBI Refseq. It worked with only one, but with others, its showing this error. How can I correct it ? 
Can you help me with this ?

**Comment by bioinfo-ut** [comment]
glistcompare has problems running in your system or with your files.
Test whether you can normally execute binaries that are located in your GenomeTester4/ folder.

**Comment by bioinfo-ut** [comment]
Also, check whether you have provided all input files and in the correct format.

**Comment by ABMolBio** [comment]
Hey, 

I already tested the GenomeTester4 binaries while running the example script. Moreover, the script is running successfully with one specific ref genome. But when I am changing the reference genome, it is showing this error. I tried with 3-4 different reference genomes. I rechecked, my reads and reference files are in correct fastq and fasta format. What should I do ?

**Comment by bioinfo-ut** [comment]
If it runs with one reference genome, then the software seems to work normally.
The problem should be in the input files.
Try to find the differences between working and non-working input files that may cause the error.
We cannot help you without having your input files.

**Comment by bala-ruokavirasto** [comment]
Hi,

For future reference, Kindly Unzip the input file genome solved this error for me.

Bala
