### ISSUE TITLE
Plasmid present in database?

### ISSUE THREAD

**Issue by SK-N-BE** [bioinfo-ut/PlasmidSeeker#3]
Hello,
I am looking for the copy number of the plasmid pHNSHP45 in E.coli isolates. The plasmid should be present. However, it was not identified by plasmidseeker. Therefore, I was wondering whether this plasmid is included in your database.
How may I check whether a plasmid is present in the database or not?

Greetings SK-N-BE

**Comment by SK-N-BE** [comment]
I checked the presence of the plasmid using BRIG. In fact, the plasmid is not present in isolate 2. However, it is present in isolate 1

![phnshp45_brig](https://user-images.githubusercontent.com/38497785/39800033-c55f4de4-5366-11e8-8115-2a796effa504.png)

**Comment by bioinfo-ut** [comment]
You can check the names of plasmids included in the database if you go under the database directory and open the text file "names.txt".

**Comment by SK-N-BE** [comment]
Hei,
thank you! The plasmid is in fact not included into the database. How may I include the plasmid into the database?

**Comment by SK-N-BE** [comment]
Hello,
I need your help.

I now builded my own database. I selected two plasmids that I found with plasmidseeker using your database (as a kind of control) . In addition, I also added the sequence of the plasmid pHNSHP45 to the database. 

I got results- when using the default values (kmer 20 and so on), plasmidseeker.pl was able to identify the two plasmids that I found before. However, it was not able to identify the pHNSHP45 plasmid. But i know, that the plasmid is present in one of my samples (see BRIG figure).

Therefore, I maked a new database, but this time, I reduced the k-mer length to 10. Now, the plasmid was found with 91,27% identity.

BUT, I got these error messages and do not know what exactly it means:

> **Warnmeldung:
In testiPlasmiidi2(bac[, 1], bac[, 2], plasmid[, 1], plasmid[, 2],  :
  Vale bakter v6i koondumisprobleem????**
tmp_list_cov_10_intrsec.list tmp_list_cov_10_intrsec.list
Total size 178258
Finding intersection
Size 89129
Sorting
Done
Printing distribution of tmp_plasmid.txt
Initial median 426
tmp_final_10_0_diff1.list tmp_final_10_0_diff1.list
Total size 163646
Finding intersection
Size 81823
Sorting
Done
FINAL median 392
Testing plasmid...
**Warnmeldung:
In testiPlasmiidi2(bac[, 1], bac[, 2], plasmid[, 1], plasmid[, 2],  :
  Vale bakter v6i koondumisprobleem????
Argument ""Tehniline" isn't numeric in sprintf at plasmidseeker.pl line 413.
Argument ""Tehniline" isn't numeric in sprintf at plasmidseeker.pl line 413.
Argument ""Tehniline" isn't numeric in sprintf at plasmidseeker.pl line 413.**

>

**Comment by SK-N-BE** [comment]
Hello,
I was trying several things in order to solve the problem described above.

I was using the default kmer of 80 when building the database but I reduced the Minimum threshold F (-f ). When I was reducing the threshold to 5 %, I suddenly also got a hit for plasmid pHNSHP45 with 5,93% identity.

But why only such a low number? As you can see, I clearly showed by using BRIG that the plasmid is present and that the identity is very high (se Figure above)

**Comment by SK-N-BE** [comment]
Hei again,
I did a mistake. I was using that isolate for which BRIG indicated that the plasmid is not present. In the other isolate, the above named plasmid is present with 77% identity (when using the default kmer) that might be correct. As you can see in the BRIG figure, there are some small regions that are not present. 

Thus, using a kmer length of only 10, gives a false positive result. 

However, is it possible to add the plasmid to the main database from you? Or do I have to build a complete new database?
