### ISSUE TITLE
cannot execute binary file

### ISSUE THREAD

**Issue by nonghor** [bioinfo-ut/PlasmidSeeker#4]
I have already installed as in the example but all 4 commands in GenomeTester4 were shown "cannot execute binary file" as below. I was wondering, what was happened ? How could I solve it ?

I use Unix (MacOS)
--2018-05-30 00:38:02--  ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR193/001/ERR1937841/ERR1937841.fastq.gz
           => ‘ERR1937841.fastq.gz’
Resolving ftp.sra.ebi.ac.uk (ftp.sra.ebi.ac.uk)... 193.62.192.7
Connecting to ftp.sra.ebi.ac.uk (ftp.sra.ebi.ac.uk)|193.62.192.7|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /vol1/fastq/ERR193/001/ERR1937841 ... done.
==> SIZE ERR1937841.fastq.gz ... 105003548
==> PASV ... done.    ==> RETR ERR1937841.fastq.gz ... done.
Length: 105003548 (100M) (unauthoritative)

ERR1937841.fastq.gz 100%[===================>] 100.14M  2.32MB/s    in 34s     

2018-05-30 00:38:37 (2.94 MB/s) - ‘ERR1937841.fastq.gz’ saved [105003548]

Unpacking files...
Identifying E. coli sample EC1
Loading database...
Converting sample reads to k-mers...
GenomeTester4/glistmaker: GenomeTester4/glistmaker: cannot execute binary file
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
Finding coverage of bacterial isolate...
GenomeTester4/glistmaker: GenomeTester4/glistmaker: cannot execute binary file
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
GenomeTester4/gdistribution: GenomeTester4/gdistribution: cannot execute binary file
Printing distribution of tmp_bacteria.txt
Initial median 0
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
GenomeTester4/gdistribution: GenomeTester4/gdistribution: cannot execute binary file
FINAL median 0
Bacteria median coverage is 0
Bacteria median coverage is too low (less than 3). Higher coverage dataset is needed or use flag --ponly at plasmidseeker.pl line 268.
Identifying E. coli sample EC2
Loading database...
Converting sample reads to k-mers...
GenomeTester4/glistmaker: GenomeTester4/glistmaker: cannot execute binary file
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
Finding coverage of bacterial isolate...
GenomeTester4/glistmaker: GenomeTester4/glistmaker: cannot execute binary file
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
GenomeTester4/gdistribution: GenomeTester4/gdistribution: cannot execute binary file
Printing distribution of tmp_bacteria.txt
Initial median 0
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
GenomeTester4/gdistribution: GenomeTester4/gdistribution: cannot execute binary file
FINAL median 0
Bacteria median coverage is 0
Bacteria median coverage is too low (less than 3). Higher coverage dataset is needed or use flag --ponly at plasmidseeker.pl line 268.
Identifying E. coli sample EC3
Loading database...
Converting sample reads to k-mers...
GenomeTester4/glistmaker: GenomeTester4/glistmaker: cannot execute binary file
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
Finding coverage of bacterial isolate...
GenomeTester4/glistmaker: GenomeTester4/glistmaker: cannot execute binary file
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
GenomeTester4/gdistribution: GenomeTester4/gdistribution: cannot execute binary file
Printing distribution of tmp_bacteria.txt
Initial median 0
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
GenomeTester4/gdistribution: GenomeTester4/gdistribution: cannot execute binary file
FINAL median 0
Bacteria median coverage is 0
Bacteria median coverage is too low (less than 3). Higher coverage dataset is needed or use flag --ponly at plasmidseeker.pl line 268.
Removing temporary files...

**Comment by bioinfo-ut** [comment]
You can try adding executable privileges (chmod +x) to the GenomeTester4 binary files and see if that solves the problem

**Comment by nonghor** [comment]
It did not work. I use Unix (MacOs).

**Comment by SK-N-BE** [comment]
I think I had the same problem. Use this command:

chmod 777 /home/username/path/to/GenomeTester4/glistmaker
chmod 777 /home/username/path/to/GenomeTester4/glistcompare
chmod 777 /home/username/path/to/GenomeTester4/gdistribution

if you can german: https://www.shellbefehle.de/befehle/chmod/

Here, it is nicely explained what you do when using this command
