### ISSUE TITLE
Error with gt4_wordmap_new

### ISSUE THREAD

**Issue by nickp60** [bioinfo-ut/PlasmidSeeker#6]
Any ideas how to deal with this error?

```
$perl plasmidseeker.pl -d ~/dbs/db_w20/ -b ~/GCA_000827105.1_ASM82710v1_genomic -i ~/reads.fastq.gz   -o ./test_1/ -t 2

Loading database...
Converting sample reads to k-mers...
gt4_wordmap_new: could not mmap file tmp_sample_20.list
gt4_wordmap_new: could not mmap file tmp_sample_20.list
Error: Creating the wordmap failed!
Finding coverage of bacterial isolate...
gt4_wordmap_new: could not mmap file tmp_sample_20.list
gt4_wordmap_new: could not mmap file tmp_closest_20.list
Error: Creating the wordmap failed!
gt4_wordmap_new: could not mmap file tmp_list_cov_20_intrsec.list
gt4_wordmap_new: could not mmap file tmp_list_cov_20_intrsec.list
Error: Creating the wordmap failed!
tmp_list_cov_20_intrsec.list tmp_list_cov_20_intrsec.list
Printing distribution of tmp_bacteria.txt
Initial median 0
gt4_wordmap_new: could not mmap file tmp_min_2_20_intrsec.list
gt4_wordmap_new: could not mmap file tmp_min_2_20_intrsec.list
Error: Creating the wordmap failed!
gt4_wordmap_new: could not mmap file tmp_min_2_20_intrsec.list
gt4_wordmap_new: could not mmap file tmp_longtail_20_intrsec.list
Error: Creating the wordmap failed!
tmp_final_20_0_diff1.list tmp_final_20_0_diff1.list
FINAL median 0
Bacteria median coverage is 0
Bacteria median coverage is too low (less than 3). Higher coverage dataset is needed or use flag --ponly at /home/nw42839/GitHub/PlasmidSeeker/plasmidseeker.pl line 268.
```

Perl version:

```
perl --version
This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi
```

**Comment by diaz13** [comment]
Hi 
I have the same error. Someone can help us ???


root@vwalf6003:/home/user/Tools/PlasmidSeeker-master# perl plasmidseeker.pl -i ../../Bureau/1 -d plasmid_db/ -b ../FTNF002-00.fasta -o result.txt
Loading database...
Converting sample reads to k-mers...
gt4_wordmap_new: could not mmap file tmp_sample_20.list
gt4_wordmap_new: could not mmap file tmp_sample_20.list
Error: Creating the wordmap failed!
Finding coverage of bacterial isolate...
gt4_wordmap_new: could not mmap file tmp_sample_20.list
Error: Creating the wordmap failed!
gt4_wordmap_new: could not mmap file tmp_list_cov_20_intrsec.list
gt4_wordmap_new: could not mmap file tmp_list_cov_20_intrsec.list
Error: Creating the wordmap failed!
tmp_list_cov_20_intrsec.list tmp_list_cov_20_intrsec.list
Printing distribution of tmp_bacteria.txt
Initial median 0
gt4_wordmap_new: could not mmap file tmp_min_2_20_intrsec.list
gt4_wordmap_new: could not mmap file tmp_min_2_20_intrsec.list
Error: Creating the wordmap failed!
gt4_wordmap_new: could not mmap file tmp_min_2_20_intrsec.list
gt4_wordmap_new: could not mmap file tmp_longtail_20_intrsec.list
Error: Creating the wordmap failed!
tmp_final_20_0_diff1.list tmp_final_20_0_diff1.list
FINAL median 0
Bacteria median coverage is 0
Bacteria median coverage is too low (less than 3). Higher coverage dataset is needed or use flag --ponly at plasmidseeker.pl line 268.

**Comment by bioinfo-ut** [comment]
Hi!

Sorry for the delay. I am looking into the problem and will let you know as soon as I have the solution.

**Comment by bioinfo-ut** [comment]
nickp60 - do not use gzipped input. At the moment, the program expects uncompressed input.

diaz13 - are you sure you are inputting a fastq file? You command line has: "-i ../../Bureau/1" as input, does not look like uncompressed fastq.

**Comment by iowa69** [comment]
Same error here with paired reads; 
fact is I have used multple datasets, in this case I have even converted my files to fasta and then to fastq again for an even format. 1.2Gb of fastq file is ok? Multiple "closest" genomes were used. When I use the example dataset everything works fine. 



iowa@iowa-y500:~/PlasmidSeeker$ perl plasmidseeker.pl -d ~/PlasmidSeeker/db_w20  -i ~/PlasmidSeeker/fakeCPp.fastq -b ~/PlasmidSeeker/mdrtj.fasta -o res.txt -t 16 
Loading database...
Converting sample reads to k-mers...
gt4_wordmap_new: could not mmap file tmp_sample_20.list
gt4_wordmap_new: could not mmap file tmp_sample_20.list
Error: Creating the wordmap failed!
Finding coverage of bacterial isolate...
gt4_wordmap_new: could not mmap file tmp_sample_20.list
Error: Creating the wordmap failed!
gt4_wordmap_new: could not mmap file tmp_list_cov_20_intrsec.list
gt4_wordmap_new: could not mmap file tmp_list_cov_20_intrsec.list
Error: Creating the wordmap failed!
tmp_list_cov_20_intrsec.list tmp_list_cov_20_intrsec.list
Printing distribution of tmp_bacteria.txt
Initial median 0
gt4_wordmap_new: could not mmap file tmp_min_2_20_intrsec.list
gt4_wordmap_new: could not mmap file tmp_min_2_20_intrsec.list
Error: Creating the wordmap failed!
gt4_wordmap_new: could not mmap file tmp_min_2_20_intrsec.list
gt4_wordmap_new: could not mmap file tmp_longtail_20_intrsec.list
Error: Creating the wordmap failed!
tmp_final_20_0_diff1.list tmp_final_20_0_diff1.list
FINAL median 0
Bacteria median coverage is 0
Bacteria median coverage is too low (less than 3). Higher coverage dataset is needed or use flag --ponly at plasmidseeker.pl line 268.

**So, 
I have tryed Fwd and Rev file separatly and it works only with my ...R2 data.**

**Comment by martroosaare** [comment]
Hi! Fastq file size should not affect whether the program works or not. From the error, it looks like your input file is not in correct fastq/fasta format. Can you look over your Fwd and Rev read files and verify if there are any differences which might cause the trouble?

What are the formats of your original files? You said you have converted them to fasta and then to fastq again? Can you describe the rationale behind it?

**Comment by iowa69** [comment]
Only rev worked for me, on all datasets analyzed. 
Data are raw fastq from Illumina, paired end.
I do not see anything abnormal with fwd file. I have used all the reads in many other programs without 
Thinking there was a problem with fwd file I converted my fastq to fasta and then to fastq again, so I was  sure to have a "perfect" fastq ma nothing changed.

**Comment by mihkelvaher** [comment]
The problem seems to be with glistmaker.
Do
`./PlasmidSeeker/GenomeTester4/glistmaker ~/PlasmidSeeker/fakeCPp.fastq -w 20 -o fakeCPp`
and
`./PlasmidSeeker/GenomeTester4/glistmaker ~/PlasmidSeeker/mdrtj.fasta -w 20 -o mdrtj`
successfully output list files? (fakeCPp_20.list and mdrtj_20.list).

You could try compiling newer GenomeTester4 (https://github.com/bioinfo-ut/GenomeTester4) and see if that works (the most recent version is on the 4_1_unstable branch).
