### ISSUE TITLE
Cannot open GenomeTester binaries

### ISSUE THREAD

**Issue by pavlo888** [bioinfo-ut/PlasmidSeeker#9]
Hi,

So I am trying to the plasmidseeker package but there seems to be an error with the GenomeTester binaries. 

I get this printout from the binary files 
GenomeTester4/glistmaker: GenomeTester4/glistmaker: cannot execute binary file
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
Finding coverage of bacterial isolate...
GenomeTester4/glistmaker: GenomeTester4/glistmaker: cannot execute binary file
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
GenomeTester4/glistcompare: GenomeTester4/glistcompare: cannot execute binary file
GenomeTester4/gdistribution: GenomeTester4/gdistribution: cannot execute binary file

I have already checked for the permissions and they are all right. 

By the way, I am running the package in an Mac OS environment. 

Thank you for your help. 

Cheers, 
Pablo

**Comment by mihkelvaher** [comment]
Hi!

The GT4 binaries are compiled in Linux.
You might want to try to compile them in OSX but after a quick test it seems compiling them there is not possible at the moment.
You can create an issue about it in the GenomeTester4 repository (https://github.com/bioinfo-ut/GenomeTester4).

All the best,
Mihkel
